# El método de k-means

In [1]:
import numpy as np

In [2]:
data = np.random.random(90).reshape(30, 3)

data

array([[ 0.02899263,  0.75336089,  0.1509988 ],
       [ 0.79712127,  0.66433522,  0.68050549],
       [ 0.56194242,  0.40797792,  0.37436031],
       [ 0.73828644,  0.89713617,  0.93264519],
       [ 0.97331243,  0.02839476,  0.60140886],
       [ 0.48317137,  0.37974681,  0.63604114],
       [ 0.82764102,  0.18539913,  0.71932766],
       [ 0.46232227,  0.38826632,  0.21314019],
       [ 0.43668384,  0.46859645,  0.93282108],
       [ 0.04431688,  0.85351707,  0.82656771],
       [ 0.40905001,  0.90327039,  0.49393473],
       [ 0.33226245,  0.34093586,  0.34871597],
       [ 0.32892669,  0.91748831,  0.8609645 ],
       [ 0.14513769,  0.84012351,  0.38768515],
       [ 0.35046045,  0.20906658,  0.0963832 ],
       [ 0.69969997,  0.02005446,  0.40817792],
       [ 0.24919468,  0.09330022,  0.40377291],
       [ 0.33715409,  0.74335255,  0.22623293],
       [ 0.18499264,  0.62244128,  0.22965781],
       [ 0.35467271,  0.06172094,  0.48108036],
       [ 0.84598976,  0.47868384,  0.216

In [3]:
c1 = np.random.choice(range(len(data)))

c2 = np.random.choice(range(len(data)))

clust_centers = np.vstack([data[c1], data[c2]])

clust_centers

array([[ 0.73828644,  0.89713617,  0.93264519],
       [ 0.79712127,  0.66433522,  0.68050549]])

In [4]:
from scipy.cluster.vq import vq

In [5]:
vq(data, clust_centers)

(array([1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 1], dtype=int32),
 array([ 0.93718969,  0.        ,  0.46341453,  0.        ,  0.66462009,
         0.42606594,  0.48147522,  0.63775758,  0.48155162,  0.70338383,
         0.49244083,  0.65632702,  0.41608621,  0.73602165,  0.86485506,
         0.70622299,  0.83838263,  0.6512888 ,  0.76139359,  0.77374096,
         0.50208329,  0.66177691,  0.16935176,  0.8568196 ,  0.61214133,
         0.27167184,  0.58788383,  0.41598634,  0.26218192,  0.97853007]))

In [6]:
from scipy.cluster.vq import kmeans

In [7]:
kmeans(data, clust_centers)

(array([[ 0.54030644,  0.77833804,  0.69375866],
        [ 0.49949967,  0.36361344,  0.32179959]]), 0.38000915145317077)

In [8]:
kmeans(data, 2)

(array([[ 0.24749921,  0.51015822,  0.31980046],
        [ 0.7455043 ,  0.49458962,  0.55602325]]), 0.37644554262039698)