# Regresión Lineal

In [3]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np

/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [4]:
data = pd.read_csv('../datasets/ads/Advertising.csv')

In [5]:
feature_cols = ['TV', 'Radio', 'Newspaper']

In [6]:
X = data[feature_cols]
Y = data['Sales']

In [7]:
estimator = SVR(kernel = 'linear')

In [9]:
selector = RFE(estimator, 2, step = 1)

selector = selector.fit(X, Y)

In [10]:
selector.support_

array([ True,  True, False], dtype=bool)

In [11]:
selector.ranking_

array([1, 1, 2])

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
X_pred = X[['TV', 'Radio']]

In [15]:
lm = LinearRegression()

lm.fit(X_pred, Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [16]:
lm.intercept_

2.9210999124051362

In [17]:
lm.coef_

array([ 0.04575482,  0.18799423])

In [18]:
lm.score(X_pred, Y)

0.89719426108289557